name: check-installation
on:
    workflow_dispatch: 
    pull_request: 
        branches: 
            - 1.x
jobs:
    run-pip-install-ubuntu-20-04:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v3
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
    run-pip-install-ubuntu-22-04:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v3
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt